version: '3'
services:
  db:
    image: couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
    - ./couchdb:/usr/local/var/lib/couchdb
    ports:
      - "5984:5984"
  webapp:
    build: .
    depends_on:
      - db
    ports:
      - 6543:6543
    links:
      - db
